# Generated by Django 4.1.7 on 2023-04-11 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemodel',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 4, 4, 6, 516864, tzinfo=datetime.timezone.utc)),
        ),
    ]
