# Generated by Django 4.1.7 on 2023-04-09 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_codemodel_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemodel',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 18, 53, 20, 669164, tzinfo=datetime.timezone.utc)),
        ),
    ]
